/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface DrainerDemoInterface extends Interface {
    getFunction(nameOrSignature: "pull"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Pulled"): EventFragment;

    encodeFunctionData(functionFragment: 'pull', values: [AddressLike, AddressLike]): string;

    decodeFunctionResult(functionFragment: 'pull', data: BytesLike): Result;
  }

  
    export namespace PulledEvent {
      export type InputTuple = [token: AddressLike, from: AddressLike, amount: BigNumberish];
      export type OutputTuple = [token: string, from: string, amount: bigint];
      export interface OutputObject {token: string, from: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface DrainerDemo extends BaseContract {
    
    connect(runner?: ContractRunner | null): DrainerDemo;
    waitForDeployment(): Promise<this>;

    interface: DrainerDemoInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    pull: TypedContractMethod<
      [token: AddressLike, from: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'pull'): TypedContractMethod<
      [token: AddressLike, from: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'Pulled'): TypedContractEvent<PulledEvent.InputTuple, PulledEvent.OutputTuple, PulledEvent.OutputObject>;

    filters: {
      
      'Pulled(address,address,uint256)': TypedContractEvent<PulledEvent.InputTuple, PulledEvent.OutputTuple, PulledEvent.OutputObject>;
      Pulled: TypedContractEvent<PulledEvent.InputTuple, PulledEvent.OutputTuple, PulledEvent.OutputObject>;
    
    };
  }